version: 2
jobs:
  build:
    branches:
      only:
        - test
    docker:
      - image: docker:18.03.0-ce-git
    steps:
      - checkout
      - setup_remote_docker
      - run:
          name: Build docker image
          command: docker build -t "demo-image" .
      - run:
          name: Create docker image and run tests
          command: docker container create --name "demo-container"  -w "/app" "$IMAGE_NAME" pipenv run pytest
      - run:
          name: Copy test results
          command: |
            mkdir -p ~/test-results/unittest
            docker cp demo-image:/app/test_results.xml ~/test-results/unittest/results.xml
          when: always
      - store_test_results:
          path: ~/test-results
